[theme]
base = "dark"

primaryColor = "#F2C94C"          # amarelo (Hurst)
backgroundColor = "#0E0E0E"       # preto principal
secondaryBackgroundColor = "#151515"  # cards / sidebar
textColor = "#FFFFFF"            # texto branco
font = "sans serif"
